version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: fastapi_app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
  db:
    image: postgres:14
    container_name: postgres_fastapi
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=next_level_app_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: