services:
  db:
    image: postgres:17
    container_name: postgres_fastapi
    restart: always
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       next_level_app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: fastapi_app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
